title: Chenxu Jia's Homepage
page-top-title: Chenxu Jia
top-section-bg-text: Computer Science
home-subtitle: Chenxu Jia&ensp;|&ensp;贾晨旭
copyright-text: '&copy; Chenxu Jia 2023-2025. All Rights Reserved.'